// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package orms

import (
	"database/sql"
)

type User struct {
	ID    int64
	Nome  string
	Email sql.NullString
	Cpf   sql.NullString
}
